name: CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    uses: szabolcsszaraz/platform-ci/.github/workflows/docker-build.yml@v1
    with:
      image_name: szabokasz/ci-test-app
      dockerfile: ./Dockerfile
      context: .
      tag: latest
    secrets: inherit
